
branches:
 only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/  # Also build tags

git:
 submodules: false

language: cpp
dist: trusty

matrix:
 include:
  # GCC Debug
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-5
    env:
     - C_COMPILER=gcc-5
     - CXX_COMPILER=g++-5
     - COMPILER_ID=GNU
     - CACHE_FILE="DebugGcc.cmake"
  # GCC Release
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-5
    env:
     - C_COMPILER=gcc-5
     - CXX_COMPILER=g++-5
     - COMPILER_ID=GNU
     - CACHE_FILE="ReleaseGcc.cmake"
  # Clang Debug
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.8
      packages:
       - clang-3.8
       # Have to install a recent version of libstdc++ (and available libc++ seems not to support C++14?)
       - g++-5
    env:
     - C_COMPILER=clang-3.8
     - CXX_COMPILER=clang++-3.8
     - COMPILER_ID=Clang
     - CACHE_FILE="DebugClang.cmake"
  # Clang Release
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.8
      packages:
       - clang-3.8
       # Have to install a recent version of libstdc++ (and available libc++ seems not to support C++14?)
       - g++-5
    env:
     - C_COMPILER=clang-3.8
     - CXX_COMPILER=clang++-3.8
     - COMPILER_ID=Clang
     - CACHE_FILE="ReleaseClang.cmake"

before_install:
 - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
 - sudo apt-get -qq update

install:
 - sudo apt-get install -y cmake
 - sudo apt-get install -y libboost-dev
 - wget http://ftp.de.debian.org/debian/pool/main/p/patchelf/patchelf_0.8-2_amd64.deb
 - sudo dpkg -i patchelf_0.8-2_amd64.deb
 - yes | sudo apt-get install -y qt58base qt58x11extras qt58imageformats qt58svg qt58tools qt58translations
 - wget https://github.com/scandyna/multidiagtools/releases/download/v0.3.6-rc3/Mdt0-0.3.6-Qt-5.8-Linux-${COMPILER_ID}-x86_64.tar.bz2 -O Mdt.tar.bz2
 - mkdir /opt/Mdt
 - tar -xjf Mdt.tar.bz2 -C /opt/Mdt --strip-components 1
 - cmake -D QT_PREFIX_PATH=/opt/qt58 -P /opt/Mdt/MdtPostInstall.cmake

before_script:
 - "export DISPLAY=:99.0"
 - sudo sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

script:
 - mkdir build
 - cd build
 - cmake -C ../cmake/caches/${CACHE_FILE} -D CMAKE_C_COMPILER=${C_COMPILER} -D CMAKE_CXX_COMPILER=${CXX_COMPILER} -D MDT_PREFIX_PATH=/opt/Mdt ..
 - make -j4
 - ctest --output-on-failure .

before_deploy:
 - cpack -G TBZ2 .

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: UqTr2SaJoMJydDtVVMJVinkWyy4uTE71IKz2gNbLGl1ZwDgJSqEz23qNxGFTwcDg/Hg5EX2TSK2AqoXomwxEMxNJhaT6+QsiMEvHLumYs1IIrkfvdb5GHcmf8xgg+8h8di/wdXSZOAWcsu18ec5a0o08jJ5jwaJxKvSYIKSI2I32d2jXsTAeipsV/AQ+f2jYpZ1YzC6Nrx1kOy159f7XuNs38Ly6WfO1Z/4qARdPq/Ns1m6X8LuUF6ZBGkO6WimTDodRidz7HNw8IKda5Fig73KbkI7SJgsVz/T3crT9I07ydfLuqSUVsdG3TRZ8KwdUZoREeBCZ3CJTIC0q79jh1DV+qaUYnXmwbPCauRJ5dcB0WZ22Y25BPZKZqjK8/ioepKzwIUe4Fb9iswXYCf3QS7+zfqkEASfS92u4yeostyrXUKDyWq8RBkN9FtNEl3/P0y6M9Emd1AvwdYH0QJUBt7VmylVorlyN1IpYIeVRMmlKZdTH2jzUrb7YxmO1vhQ4rVwXvYpF9JSoX0vlYdKi9M8MghuK4EZ66mdR572VdyloKxPQIt/2qNea1bFRPiVJwJQg3CJ/3sWKHubUxGaCKoqK6/a2m4wVTW/cePQe+vuMVNtEtREcLQz91JrXaVRsjHqU2pKciksiIisaOjAALPyQpLLq6anUTdn6ROWLhHs=
  file_glob: true
  file: MdtAppExample-*.tar.bz2
  on:
    tags: true
